import he from "he";
import Head from "next/head";
import Image from "next/image";
import hydrate from "next-mdx-remote/hydrate";
import renderToString from "next-mdx-remote/render-to-string";

import { getPortfolioItem, getPortfolioSlugs } from "../../lib/data";

export const getStaticPaths = async () => {
  const slugsRes = await getPortfolioSlugs();
  const slugs = slugsRes.portfolios;

  return {
    paths: slugs.map((slug) => ({ params: { slug: slug.slug } })),
    fallback: false,
  };
};

export const getStaticProps = async ({ params }) => {
  const portfolioItem = await getPortfolioItem(params.slug);
  return {
    props: {
      portfolioItem: portfolioItem.portfolios[0],
      content: await renderToString(he.decode(portfolioItem.portfolios[0].content)),
    },
  };
};

export default function Home({ portfolioItem, content }) {
  console.log(portfolioItem);

  return (
    <div>
      <Head>
        <title>Ascend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>{portfolioItem.title}</h1>
        <p>{portfolioItem.description}</p>
        <span>{new Date(portfolioItem.date).toDateString()}</span>
        <Image
          src={portfolioItem.coverImage.url}
          height={portfolioItem.coverImage.height}
          width={portfolioItem.coverImage.width}
        />
        <div>
          {portfolioItem.tags.map((tag) => (
            <span key={tag}> {tag}</span>
          ))}
        </div>
        <div>{hydrate(content)}</div>
      </div>
    </div>
  );
}
